//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FemsaEP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class acessorio_SAP
    {
        public string MANDT { get; set; }
        public decimal ZCODIGOACCESORIOS { get; set; }
        public string ZNOMBREACCESORIOS { get; set; }
        public string ZDESACTIVADO { get; set; }
    }
}
