//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FemsaEP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class administrador
    {
        public administrador()
        {
            this.chat_mensagem = new HashSet<chat_mensagem>();
            this.manutencao = new HashSet<manutencao>();
            this.mensagem = new HashSet<mensagem>();
        }
    
        public int id { get; set; }
        public string codigo { get; set; }
        public string nome { get; set; }
        public string login { get; set; }
        public string email { get; set; }
        public string senha { get; set; }
        public string mandante { get; set; }
    
        public virtual ICollection<chat_mensagem> chat_mensagem { get; set; }
        public virtual ICollection<manutencao> manutencao { get; set; }
        public virtual ICollection<mensagem> mensagem { get; set; }
    }
}
