//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FemsaEP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ativacao_foto
    {
        public int id { get; set; }
        public Nullable<int> id_ativacao { get; set; }
        public string url_foto { get; set; }
        public Nullable<int> etapa { get; set; }
        public Nullable<decimal> id_peca { get; set; }
        public Nullable<byte> executivo { get; set; }
        public string mandante { get; set; }
        public Nullable<System.DateTime> criacao { get; set; }
    
        public virtual ativacao ativacao { get; set; }
        public virtual peca_SAP peca_SAP { get; set; }
    }
}
