//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FemsaEP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ativacao
    {
        public ativacao()
        {
            this.ativacao_foto = new HashSet<ativacao_foto>();
            this.ativacao_mensagem = new HashSet<ativacao_mensagem>();
            this.ativacao_peca = new HashSet<ativacao_peca>();
            this.contrapartida_ativacoes = new HashSet<contrapartida_ativacoes>();
            this.mensagem = new HashSet<mensagem>();
        }
    
        public int id { get; set; }
        public string codigo { get; set; }
        public Nullable<decimal> custo_valor { get; set; }
        public string descricao { get; set; }
        public Nullable<int> id_cliente { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> id_projeto { get; set; }
        public string situacao { get; set; }
        public Nullable<byte> executivo { get; set; }
        public Nullable<System.DateTime> criacao { get; set; }
        public string mandante { get; set; }
        public Nullable<System.DateTime> data_finalizacao { get; set; }
        public string ZCLIENTE { get; set; }
    
        public virtual ICollection<ativacao_foto> ativacao_foto { get; set; }
        public virtual ICollection<ativacao_mensagem> ativacao_mensagem { get; set; }
        public virtual ICollection<ativacao_peca> ativacao_peca { get; set; }
        public virtual projeto projeto { get; set; }
        public virtual status_ativacao status_ativacao { get; set; }
        public virtual cliente_SAP cliente_SAP { get; set; }
        public virtual ICollection<contrapartida_ativacoes> contrapartida_ativacoes { get; set; }
        public virtual ICollection<mensagem> mensagem { get; set; }
    }
}
