//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FemsaEP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class canal_SAP
    {
        public canal_SAP()
        {
            this.cliente_SAP = new HashSet<cliente_SAP>();
        }
    
        public Nullable<decimal> MANDT { get; set; }
        public string ZCODCANAL { get; set; }
        public string ZNOMCANAL { get; set; }
        public string ZDESACTIV { get; set; }
    
        public virtual ICollection<cliente_SAP> cliente_SAP { get; set; }
    }
}
