//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FemsaEP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class caracteristica_de_peca_SAP
    {
        public Nullable<decimal> MANDT { get; set; }
        public decimal ZCODPIEZA { get; set; }
        public Nullable<decimal> ZCODIPECA { get; set; }
        public Nullable<decimal> ZCODMARCA { get; set; }
        public Nullable<decimal> ZCODEMBAL { get; set; }
        public Nullable<decimal> ZCODALIME { get; set; }
        public string ZCODIMAGEN { get; set; }
        public string ZDETALLE { get; set; }
        public Nullable<decimal> ZCODKITS { get; set; }
        public string ZFORMCUS { get; set; }
        public Nullable<decimal> ZCOSTOM2 { get; set; }
        public Nullable<decimal> ZANCHO { get; set; }
        public Nullable<decimal> ZALTURA { get; set; }
        public Nullable<decimal> ZDIAMETRO { get; set; }
        public Nullable<decimal> ZPROVEEDO { get; set; }
        public Nullable<decimal> ZVALORPZA { get; set; }
        public string ZDESACTIV { get; set; }
        public string valor { get; set; }
        public string foto_url { get; set; }
    
        public virtual alimento_SAP alimento_SAP { get; set; }
        public virtual embalagem_SAP embalagem_SAP { get; set; }
        public virtual peca_SAP peca_SAP { get; set; }
        public virtual marca_SAP marca_SAP { get; set; }
    }
}
