//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FemsaEP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cliente_cluster_SAP
    {
        public string ZCLIENTE { get; set; }
        public Nullable<decimal> ZCODCLUSTER { get; set; }
        public int id { get; set; }
    
        public virtual cliente_SAP cliente_SAP { get; set; }
        public virtual cluster_SAP cluster_SAP { get; set; }
    }
}
