//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FemsaEP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cliente_SAP
    {
        public cliente_SAP()
        {
            this.ativacao = new HashSet<ativacao>();
            this.cliente_cluster_SAP = new HashSet<cliente_cluster_SAP>();
            this.cliente_projeto = new HashSet<cliente_projeto>();
            this.manutencao = new HashSet<manutencao>();
        }
    
        public Nullable<decimal> MANDT { get; set; }
        public string ZCLIENTE { get; set; }
        public string ZNOMBRE { get; set; }
        public string ZNOMFANTA { get; set; }
        public string ZCNPJCPFI { get; set; }
        public Nullable<decimal> ZCEP { get; set; }
        public string ZDIRECCIO { get; set; }
        public string ZBARRIO { get; set; }
        public string ZCIUDAD { get; set; }
        public string ZUF { get; set; }
        public Nullable<decimal> ZPUNTOREF { get; set; }
        public string ZTERRITOR { get; set; }
        public string ZUNIDAD { get; set; }
        public string ZTELEFONO { get; set; }
        public string ZCANAL { get; set; }
        public string ZGEC { get; set; }
        public string ZNSE { get; set; }
        public string ZRUTA { get; set; }
        public Nullable<decimal> ZZAT { get; set; }
        public Nullable<decimal> ZKIT { get; set; }
        public Nullable<decimal> ZMARCAGDM { get; set; }
        public Nullable<decimal> ZLOCALIZA { get; set; }
        public Nullable<decimal> ZNOMSHOPP { get; set; }
        public string ZRED { get; set; }
        public string ZNOMBRERE { get; set; }
        public string ZHABACTIV { get; set; }
        public string ZHABRMANT { get; set; }
        public string ZHABSHOPP { get; set; }
        public string descricao { get; set; }
        public string id_novo { get; set; }
        public string id_antigo { get; set; }
        public Nullable<decimal> id_cluster { get; set; }
        public string executivo { get; set; }
        public string prospector { get; set; }
        public string desenvolvedor { get; set; }
        public string fornecedor { get; set; }
        public string design { get; set; }
        public string zona_transporte { get; set; }
        public string regional { get; set; }
        public string numero { get; set; }
        public string lattext { get; set; }
        public string longtext { get; set; }
        public Nullable<int> status_ativacao { get; set; }
        public Nullable<decimal> id_colaborador { get; set; }
        public Nullable<decimal> custo_budget { get; set; }
        public Nullable<decimal> motivo_id { get; set; }
        public string motivotxt { get; set; }
        public string cidade_limpa { get; set; }
        public string segundo_telefone { get; set; }
        public Nullable<int> id_executivo { get; set; }
        public Nullable<int> id_prospector { get; set; }
        public string ano_cliente { get; set; }
        public Nullable<int> acessooffline { get; set; }
        public Nullable<int> id_franquia { get; set; }
        public string recusa_foto { get; set; }
        public Nullable<System.DateTime> ativacao_ultima_atualizacao { get; set; }
        public string observacao { get; set; }
        public Nullable<int> pendente_retorno { get; set; }
        public string motivo_retorno { get; set; }
        public string carta_foto { get; set; }
    
        public virtual ICollection<ativacao> ativacao { get; set; }
        public virtual canal_SAP canal_SAP { get; set; }
        public virtual ICollection<cliente_cluster_SAP> cliente_cluster_SAP { get; set; }
        public virtual ICollection<cliente_projeto> cliente_projeto { get; set; }
        public virtual cluster_SAP cluster_SAP { get; set; }
        public virtual colaborador_SAP colaborador_SAP { get; set; }
        public virtual executivo executivo1 { get; set; }
        public virtual franquia franquia { get; set; }
        public virtual prospector prospector1 { get; set; }
        public virtual motivo_de_recuso_SAP motivo_de_recuso_SAP { get; set; }
        public virtual status_ativacao status_ativacao1 { get; set; }
        public virtual localizacao_SAP localizacao_SAP { get; set; }
        public virtual territorio_SAP territorio_SAP { get; set; }
        public virtual unidade_SAP unidade_SAP { get; set; }
        public virtual kit_SAP kit_SAP { get; set; }
        public virtual zat_SAP zat_SAP { get; set; }
        public virtual ICollection<manutencao> manutencao { get; set; }
    }
}
