//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FemsaEP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cluster_SAP
    {
        public cluster_SAP()
        {
            this.cliente_cluster_SAP = new HashSet<cliente_cluster_SAP>();
            this.cliente_SAP = new HashSet<cliente_SAP>();
            this.cluster_peca_SAP = new HashSet<cluster_peca_SAP>();
            this.enquete = new HashSet<enquete>();
            this.projeto_cluster = new HashSet<projeto_cluster>();
        }
    
        public Nullable<decimal> MANDT { get; set; }
        public decimal ZCODCLUST { get; set; }
        public string ZNOMBRE { get; set; }
        public string ZGPOCANAL { get; set; }
        public string ZCANAL { get; set; }
        public string ZGEC { get; set; }
        public string ZNSE { get; set; }
        public string descricao { get; set; }
        public string foco { get; set; }
        public string sigla { get; set; }
        public string atributo4 { get; set; }
    
        public virtual ICollection<cliente_cluster_SAP> cliente_cluster_SAP { get; set; }
        public virtual ICollection<cliente_SAP> cliente_SAP { get; set; }
        public virtual ICollection<cluster_peca_SAP> cluster_peca_SAP { get; set; }
        public virtual ICollection<enquete> enquete { get; set; }
        public virtual ICollection<projeto_cluster> projeto_cluster { get; set; }
    }
}
