//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FemsaEP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class contrapartida_ativacoes
    {
        public int id { get; set; }
        public Nullable<int> id_contrapartida { get; set; }
        public Nullable<int> id_ativacao { get; set; }
        public Nullable<int> etapa { get; set; }
        public string mandante { get; set; }
        public Nullable<decimal> ZCODCONPA { get; set; }
    
        public virtual ativacao ativacao { get; set; }
        public virtual contrapartida_SAP contrapartida_SAP { get; set; }
    }
}
