//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FemsaEP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class enquete
    {
        public enquete()
        {
            this.enquete_perguntas = new HashSet<enquete_perguntas>();
            this.enquete_resposta = new HashSet<enquete_resposta>();
        }
    
        public int id { get; set; }
        public string titulo { get; set; }
        public string vigencia { get; set; }
        public Nullable<System.DateTime> data_limite { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> data_inicio { get; set; }
        public string mandante { get; set; }
        public Nullable<decimal> ZCODCLUST { get; set; }
    
        public virtual cluster_SAP cluster_SAP { get; set; }
        public virtual ICollection<enquete_perguntas> enquete_perguntas { get; set; }
        public virtual ICollection<enquete_resposta> enquete_resposta { get; set; }
    }
}
