//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FemsaEP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class fornecedor
    {
        public int id { get; set; }
        public string codigo { get; set; }
        public string descricao { get; set; }
        public string nome { get; set; }
        public string contato { get; set; }
        public string telefone { get; set; }
        public string email { get; set; }
        public Nullable<decimal> codigo_sap { get; set; }
        public string mandante { get; set; }
    }
}
