//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FemsaEP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class manutencao_peca
    {
        public Nullable<int> id_manutencao { get; set; }
        public int id { get; set; }
        public Nullable<int> substituido { get; set; }
        public string mandante { get; set; }
        public Nullable<decimal> ZCODPECA { get; set; }
    
        public virtual manutencao manutencao { get; set; }
        public virtual peca_SAP peca_SAP { get; set; }
    }
}
