//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FemsaEP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class manutencao
    {
        public manutencao()
        {
            this.manutencao_instalacao = new HashSet<manutencao_instalacao>();
            this.manutencao_peca = new HashSet<manutencao_peca>();
        }
    
        public Nullable<System.DateTime> data_manutencao { get; set; }
        public Nullable<System.DateTime> data_ativacao { get; set; }
        public string meta_manutencao { get; set; }
        public string observacao_1 { get; set; }
        public string observacao_2 { get; set; }
        public string numero_rc { get; set; }
        public Nullable<System.DateTime> data_rc { get; set; }
        public string url_foto { get; set; }
        public string solicitante { get; set; }
        public Nullable<int> manutencao_tipo { get; set; }
        public Nullable<int> manutencao_validacao { get; set; }
        public string codigo { get; set; }
        public int id { get; set; }
        public Nullable<int> id_administrador { get; set; }
        public Nullable<byte> substituida { get; set; }
        public string mandante { get; set; }
        public string executivo_vendas { get; set; }
        public string executivo_trade { get; set; }
        public string prospector { get; set; }
        public string pos_venda { get; set; }
        public string ZCLIENTE { get; set; }
        public Nullable<decimal> ZCODPECA { get; set; }
    
        public virtual administrador administrador { get; set; }
        public virtual cliente_SAP cliente_SAP { get; set; }
        public virtual ICollection<manutencao_instalacao> manutencao_instalacao { get; set; }
        public virtual ICollection<manutencao_peca> manutencao_peca { get; set; }
        public virtual tipo_de_manutencao tipo_de_manutencao { get; set; }
        public virtual validacao validacao { get; set; }
        public virtual peca_SAP peca_SAP { get; set; }
    }
}
