//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FemsaEP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class marca_SAP
    {
        public marca_SAP()
        {
            this.caracteristica_de_peca_SAP = new HashSet<caracteristica_de_peca_SAP>();
        }
    
        public Nullable<decimal> MANDT { get; set; }
        public decimal ZCODMARCA { get; set; }
        public string ZNOMMARCA { get; set; }
        public string ZDESACTIV { get; set; }
        public Nullable<int> id_familia { get; set; }
        public string descricao { get; set; }
    
        public virtual ICollection<caracteristica_de_peca_SAP> caracteristica_de_peca_SAP { get; set; }
        public virtual familia familia { get; set; }
    }
}
