//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FemsaEP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mensagem
    {
        public mensagem()
        {
            this.chat_mensagem = new HashSet<chat_mensagem>();
        }
    
        public int id { get; set; }
        public string texto { get; set; }
        public Nullable<int> id_cliente { get; set; }
        public Nullable<int> administrador_id { get; set; }
        public byte[] hora { get; set; }
        public string status { get; set; }
        public string titulo { get; set; }
        public Nullable<int> grupo_id { get; set; }
        public string destinatario { get; set; }
        public string mandante { get; set; }
        public Nullable<decimal> ZCODGRUPO { get; set; }
        public Nullable<decimal> ZCODCOLAB { get; set; }
    
        public virtual administrador administrador { get; set; }
        public virtual ativacao ativacao { get; set; }
        public virtual ICollection<chat_mensagem> chat_mensagem { get; set; }
        public virtual colaborador_SAP colaborador_SAP { get; set; }
        public virtual grupo_SAP grupo_SAP { get; set; }
    }
}
