//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FemsaEP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class nse_SAP
    {
        public Nullable<decimal> MANDT { get; set; }
        public string ZCODNSE { get; set; }
        public string ZNOMNSE { get; set; }
        public string ZDESACTIV { get; set; }
    }
}
