//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FemsaEP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class peca_SAP
    {
        public peca_SAP()
        {
            this.ativacao_foto = new HashSet<ativacao_foto>();
            this.ativacao_peca = new HashSet<ativacao_peca>();
            this.caracteristica_de_peca_SAP = new HashSet<caracteristica_de_peca_SAP>();
            this.cluster_peca_SAP = new HashSet<cluster_peca_SAP>();
            this.manutencao = new HashSet<manutencao>();
            this.manutencao_peca = new HashSet<manutencao_peca>();
        }
    
        public Nullable<decimal> MANDT { get; set; }
        public decimal ZCODPECA { get; set; }
        public string ZNOMPECA { get; set; }
        public string ZDESACTIV { get; set; }
        public string descricao { get; set; }
    
        public virtual ICollection<ativacao_foto> ativacao_foto { get; set; }
        public virtual ICollection<ativacao_peca> ativacao_peca { get; set; }
        public virtual ICollection<caracteristica_de_peca_SAP> caracteristica_de_peca_SAP { get; set; }
        public virtual ICollection<cluster_peca_SAP> cluster_peca_SAP { get; set; }
        public virtual ICollection<manutencao> manutencao { get; set; }
        public virtual ICollection<manutencao_peca> manutencao_peca { get; set; }
    }
}
