//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FemsaEP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class projeto
    {
        public projeto()
        {
            this.ativacao = new HashSet<ativacao>();
            this.cliente_projeto = new HashSet<cliente_projeto>();
            this.contrapartida_projeto = new HashSet<contrapartida_projeto>();
            this.projeto_cluster = new HashSet<projeto_cluster>();
        }
    
        public int id { get; set; }
        public string codigo { get; set; }
        public string descricao { get; set; }
        public string observacao { get; set; }
        public string mandante { get; set; }
    
        public virtual ICollection<ativacao> ativacao { get; set; }
        public virtual ICollection<cliente_projeto> cliente_projeto { get; set; }
        public virtual ICollection<contrapartida_projeto> contrapartida_projeto { get; set; }
        public virtual ICollection<projeto_cluster> projeto_cluster { get; set; }
    }
}
