//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FemsaEP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rota_SAP
    {
        public Nullable<decimal> MANDT { get; set; }
        public decimal ZCODIRUTA { get; set; }
        public Nullable<decimal> ZEJECVTAS { get; set; }
        public Nullable<decimal> ZPOSPECTO { get; set; }
        public Nullable<decimal> ZDESARROL { get; set; }
        public Nullable<decimal> ZPROVEEDO { get; set; }
        public Nullable<decimal> ZORIGENMW { get; set; }
        public Nullable<decimal> ZDISENADO { get; set; }
        public Nullable<decimal> ZGTECOMER { get; set; }
        public Nullable<decimal> ZGTEREGIO { get; set; }
        public Nullable<decimal> ZEJECTRAD { get; set; }
        public Nullable<decimal> ZPROMOTOR { get; set; }
        public Nullable<decimal> ZCONSULTO { get; set; }
        public Nullable<decimal> ZUNIDAD { get; set; }
        public string ZDESACTIV { get; set; }
        public string descricao { get; set; }
        public Nullable<int> id_colaborador { get; set; }
    }
}
