//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FemsaEP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rota_colaborador
    {
        public int id { get; set; }
        public Nullable<decimal> id_colaborador { get; set; }
        public string lattext { get; set; }
        public string longtext { get; set; }
        public Nullable<System.DateTime> created { get; set; }
        public Nullable<decimal> km { get; set; }
    
        public virtual colaborador_SAP colaborador_SAP { get; set; }
    }
}
