//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FemsaEP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class territorio_SAP
    {
        public territorio_SAP()
        {
            this.cliente_SAP = new HashSet<cliente_SAP>();
            this.colaborador_SAP = new HashSet<colaborador_SAP>();
            this.provedor_SAP = new HashSet<provedor_SAP>();
            this.unidade_SAP = new HashSet<unidade_SAP>();
            this.zat_SAP = new HashSet<zat_SAP>();
        }
    
        public Nullable<decimal> MANDT { get; set; }
        public string ZCODTERRI { get; set; }
        public string ZNOMBRE { get; set; }
        public string ZCEP { get; set; }
        public string ZDIRECCIO { get; set; }
        public string ZBARRIO { get; set; }
        public string ZCIUDAD { get; set; }
        public string ZUF { get; set; }
        public string ZDESACTIV { get; set; }
        public Nullable<decimal> ZCENTRALI { get; set; }
        public Nullable<decimal> ZCOORDIPA { get; set; }
        public Nullable<decimal> ZAPROVCAN { get; set; }
        public string descricao { get; set; }
    
        public virtual ICollection<cliente_SAP> cliente_SAP { get; set; }
        public virtual ICollection<colaborador_SAP> colaborador_SAP { get; set; }
        public virtual ICollection<provedor_SAP> provedor_SAP { get; set; }
        public virtual ICollection<unidade_SAP> unidade_SAP { get; set; }
        public virtual ICollection<zat_SAP> zat_SAP { get; set; }
    }
}
