//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FemsaEP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class uf
    {
        public uf()
        {
            this.carta = new HashSet<carta>();
        }
    
        public int id { get; set; }
        public string uf_sigla { get; set; }
        public string mandante { get; set; }
    
        public virtual ICollection<carta> carta { get; set; }
    }
}
