//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FemsaEP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class unidade_SAP
    {
        public unidade_SAP()
        {
            this.cliente_SAP = new HashSet<cliente_SAP>();
            this.colaborador_SAP = new HashSet<colaborador_SAP>();
            this.zat_SAP = new HashSet<zat_SAP>();
        }
    
        public Nullable<decimal> MANDT { get; set; }
        public string ZCODUNIDA { get; set; }
        public string ZNOMBRE { get; set; }
        public string ZTERRITOR { get; set; }
        public Nullable<decimal> ZGTECOMER { get; set; }
        public string ZDESACTIV { get; set; }
        public string descricao { get; set; }
    
        public virtual ICollection<cliente_SAP> cliente_SAP { get; set; }
        public virtual ICollection<colaborador_SAP> colaborador_SAP { get; set; }
        public virtual territorio_SAP territorio_SAP { get; set; }
        public virtual ICollection<zat_SAP> zat_SAP { get; set; }
    }
}
