//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FemsaEP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class zat_SAP
    {
        public zat_SAP()
        {
            this.cliente_SAP = new HashSet<cliente_SAP>();
        }
    
        public Nullable<decimal> MANDT { get; set; }
        public decimal ZCODZATS { get; set; }
        public string ZNOMBRE { get; set; }
        public string ZTERRITOR { get; set; }
        public string ZUNIDAD { get; set; }
        public string ZCIUDAD { get; set; }
        public string ZUF { get; set; }
        public string ZANO { get; set; }
        public string descricao { get; set; }
        public string regiao { get; set; }
    
        public virtual ICollection<cliente_SAP> cliente_SAP { get; set; }
        public virtual territorio_SAP territorio_SAP { get; set; }
        public virtual unidade_SAP unidade_SAP { get; set; }
    }
}
